#!/bin/bash

your_id="4l93qfj"
your_gpg_email="4l93qfj@vote.gov"
govt_gpg="justinthompson593@gmail.com"

#git clone https://github.com/justinthompson593/Vote.git
#cd Vote
#git checkout -b $your_id
echo "Voter record" > voter_record.txt
echo "" >> voter_record.txt
echo "Fingerprint" >> voter_record.txt
echo "$(gpg --fingerprint $your_gpg_email)" >> voter_record.txt
echo "">> voter_record.txt
echo "DOB: 01-Jan-1970" >> voter_record.txt
echo "" >> voter_record.txt
echo "ZIP: 78102" >> voter_record.txt
echo "" >> voter_record.txt
echo "SOC: 1234" >> voter_record.txt
echo "" >> voter_record.txt
echo "Public Key"
gpg --output publickey.asc --armor --export $your_gpg_email
echo "$(<publickey.asc)" >> voter_record.txt 


echo "# Voter $your_id" > README.md
echo "" >> README.md
echo "---" >> README.md
echo "$(gpg --fingerprint $your_gpg_email)" >> README.md
echo "" >> README.md 
echo "---" >> README.md
echo "$(<publickey.asc)" >> README.md 

gpg --encrypt --armor -r $your_gpg_email -r $govt_gpg voter_record.txt && rm voter_record.txt


git add -A
git commit -m "New Registered Voter: $your_id \nVarious info that we'd want public..."
#git push origin $your_id
git push origin main
